version: 2

models:
  - name: survival_ml_model_prediction
    config:
      materialized: table  # table indicates the predictions will be written to the underlying table
    meta:
      layer:
        fabric: 'local'
